=== DalavanCloud/dukecon_server/api/src/main/resources/raml/meta_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "DukeCon Meta Schema",
  "javaType": "org.dukecon.server.api.model.MetaData",
  "type": "object",
  "properties": {
    "conference": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "tracks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/property_bag"
      }
    },
    "levels": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/property_bag"
      }
    },
    "types": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/property_bag"
      }
    }
  },
  "definitions": {
    "property_bag": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "values": {
          "$ref": "#/definitions/props"
        }
      }
    },
    "props": {
      "type": "object",
      "properties": {
        "de": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      }
    }
  }
}

=== DalavanCloud/dukecon_server/api/src/main/resources/raml/meta_example.json
{
  "conference": {
    "name": "JavaLand",
    "url": "http://javaland.eu"
  },
  "tracks": [
    {
      "key": "iot",
      "values": {
        "de": "Internet of Things",
        "en": "Internet of Things"
      }
    },
    {
      "key": "iot",
      "values": {
        "de": "Internet of Things",
        "en": "Internet of Things"
      }
    },
    {
      "key": "jvmlang",
      "values": {
        "de": "JVM Sprachen",
        "en": "JVM languages"
      }
    }
  ],
  "levels": [
    {
      "key": "beginner",
      "value": {
        "de": "Einsteiger",
        "en": "Beginner"
      }
    },
    {
      "key": "advanced",
      "value": {
        "de": "Fortgeschritten",
        "en": "Advanced"
      }
    },
    {
      "key": "expert",
      "value": {
        "de": "Experte",
        "en": "Expert"
      }
    }
  ],
  "types": [
    {
      "key": "projectreport",
      "value": {
        "de": "Projektbericht",
        "en": "Project Report"
      },
      "key": "newfeatures",
      "value": {
        "de": "Neue Features",
        "en": "New Features"
      }
    }
  ]
}
